TRAIN:
  BATCH_SIZE: 64
  DROPOUT: 0

MODEL:
  BACKBONE: 'trn'
  BACKBONE_DIM: '2D'
  BASE_MODEL: 'resnet50'
#  TRANSFORMER: True
#  ALIGNMENT: True

DATASET:
  MODE: 'test'
#  TXT_PATH: '/p300/dataset/ActionVerification/test.txt'
#  NUM_CLASS: 45
  TXT_PATH: '/p300/dataset/COIN/test.txt'
#  TXT_PATH: '/ssd0/qyc/dataset/COIN/test.txt'
#  TXT_PATH: '/p300/dataset/COIN/val.txt'
#  TXT_PATH: '/ssd0/qyc/dataset/COIN/val.txt'
  NUM_CLASS: 303
  NUM_CLIP: 16
  LEN_CLIP: 1
  AUGMENT: False



