TRAIN:
  BATCH_SIZE: 16

MODEL:
  BACKBONE: 'c3d'
  BACKBONE_DIM: '3D'
  TRANSFORMER: False
  ALIGNMENT: False

DATASET:
  MODE: 'test'
  TXT_PATH: '/p300/dataset/ActionVerification/test.txt'
  NUM_CLASS: 45
  NUM_SAMPLE: 300
  NUM_CLIP: 16
  LEN_CLIP: 1
  AUGMENT: False



