TRAIN:
  BATCH_SIZE: 128

MODEL:
  BACKBONE: 'resnet50'
  BACKBONE_DIM: '2D'
  TRANSFORMER: True
#  ALIGNMENT: True

DATASET:
  MODE: 'test'
  TXT_PATH: '/p300/dataset/ActionVerification/test_large.txt'
  NUM_CLASS: 45
  NUM_CLIP: 16
  LEN_CLIP: 1
  AUGMENT: False
  NUM_WORKERS: 16



