TRAIN:
  USE_CUDA: True
  MAX_EPOCH: 120
  DECAY_EPOCHS: 40
  DECAY_RATE: 0.1
  BATCH_SIZE: 16
  LR: 0.001
  SAVE_PATH: 'logs/resnet50+sa_img-pre_lr0.001'

MODEL:
  BACKBONE: 'resnet50'
  BACKBONE_DIM: '2D'
  PRETRAIN: True
  PRETRAIN_PATH: 'pretrained_models/resnet50-ImageNet.pth'
#  PRETRAIN_PATH: 'logs/resnet18_lr0.001_pretrain/save_models/30_checkpoint.tar'
  DIM_EMBEDDING: 128
  TRANSFORMER: False
  ALIGNMENT: True

DATASET:
  MODE: 'train'
  TXT_PATH: '/p300/dataset/ActionVerification/pretrain.txt'
  NUM_CLASS: 45
  NUM_SAMPLE: 800
  NUM_CLIP: 16
  LEN_CLIP: 24




