TRAIN:
  USE_CUDA: True
  MAX_EPOCH: 200
  DECAY_EPOCHS: 30
  DECAY_RATE: 0.1
  BATCH_SIZE: 16
  LR: 0.0001
  DROPOUT: 0.0
  PARTIAL_BN: False
  FREEZE_BACKBONE: False
  USE_ISDA: False
#  PREFETCH: True
  SEED: 1234
#  GRAD_MAX_NORM: 10
#  USE_ADAMW: True
#  FIX_VIT_PROJECTION: True

#  SAVE_PATH: 'cv_logs/resnet50-kin+vit+newsa_lr0.0001_new'
#  SAVE_PATH: 'cv_logs/test'

#  SAVE_PATH: 'coin_logs/resnet50-kin+vit+newsa_lr0.0001_s2_new'
#  SAVE_PATH: 'coin_logs/test'

  SAVE_PATH: 'diving_logs/resnet50-kin+vit+newsa_lr0.0001_s1_new'
#  SAVE_PATH: 'diving_logs/test'

MODEL:
  BACKBONE: 'cat'
  BACKBONE_DIM: '2D'
  BASE_MODEL: 'resnet50'
#  PRETRAIN: 'pretrained_models/resnet50-ImageNet.pth'
  PRETRAIN: 'pretrained_models/resnet50-kinetics400.pth'
#  PRETRAIN: 'pretrained_models/resnet50-kinetics700.pth'
#  PRETRAIN: 'pretrained_models/resnet50-mit.pth'
#  PRETRAIN: 'pretrained_models/resnet50-sthv2.pth'
#  PRETRAIN: 'pretrained_models/resnet50-ucf101.pth'
#  PRETRAIN: 'coin_logs/resnet50-kin+vit_lr0.0001_cls+triplet1/save_models/epoch_36.tar'
  DIM_EMBEDDING: 128
  TRANSFORMER: True
  ALIGNMENT: True
#  SEQ_LOSS_COEF: 0.1
#  NORM_LOSS_COEF: 0.01
#  COSFACE: True
  SAVE_EPOCHS: 1



DATASET:
  MODE: 'train'
#  TXT_PATH: '/p300/dataset/ActionVerification/splits/train_all.txt'
#  NUM_CLASS: 45

#  TXT_PATH: '/p300/dataset/COIN/splits/train_all.txt'
#  NUM_CLASS: 330

#  TXT_PATH: '/p300/dataset/COIN/splits/train_all1.txt'
#  NUM_CLASS: 72

#  TXT_PATH: '/p300/dataset/COIN/splits/train_all2.txt'
#  TXT_PATH: '/p300/dataset/COIN/splits/train_all2_ssd.txt'
#  TXT_PATH: '/p300/dataset/COIN/splits/train2_flow.txt'
#  NUM_CLASS: 37

#  TXT_PATH: '/p300/dataset/COIN/splits/train_triplet.txt'
#  NUM_CLASS: 1396

  TXT_PATH: '/p300/dataset/Diving48/splits/train_all1.txt'
  NUM_CLASS: 20



  NUM_SAMPLE: 1600
  NUM_CLIP: 16
  LEN_CLIP: 1
  SHUFFLE: True
  NUM_WORKERS: 4




