TRAIN:
  USE_CUDA: True
  MAX_EPOCH: 200
  DECAY_EPOCHS: 30
  DECAY_RATE: 0.1
  BATCH_SIZE: 16
  LR: 0.0001
  DROPOUT: 0.0
  PARTIAL_BN: False
#  GRAD_MAX_NORM: 1
#  USE_ADAMW: True
#  FIX_VIT_PROJECTION: True
#  SAVE_PATH: 'logs/test'
#  SAVE_PATH: 'cv_logs/trn-res-kin_lr0.0001'
  SAVE_PATH: 'coin_logs/trn-res-kin_lr0.0001_s2'
#  SAVE_PATH: 'diving_logs/trn-res-kin_lr0.0001'

MODEL:
  BACKBONE: 'trn'
  BACKBONE_DIM: '2D'
#  BASE_MODEL: 'BNInception'
#  PRETRAIN: 'imagenet'
  BASE_MODEL: 'resnet50'
  PRETRAIN: 'pretrained_models/resnet50-kinetics400.pth'
#  PRETRAIN: 'pretrained_models/resnet50-ImageNet.pth'
  DIM_EMBEDDING: 128
#  TRANSFORMER: True
#  ALIGNMENT: True
#  COSFACE: True
  SAVE_EPOCHS: 1

DATASET:
  MODE: 'train'
#  TXT_PATH: '/p300/dataset/ActionVerification/splits/train_all.txt'
#  NUM_CLASS: 45

#  TXT_PATH: '/p300/dataset/COIN/splits/train_all.txt'
#  NUM_CLASS: 330

#  TXT_PATH: '/p300/dataset/COIN/splits/train_all1.txt'
#  NUM_CLASS: 72

  TXT_PATH: '/p300/dataset/COIN/splits/train_all2.txt'
#  TXT_PATH: '/p300/dataset/COIN/splits/train_all2_ssd.txt'
#  TXT_PATH: '/p300/dataset/COIN/splits/train2_flow.txt'
  NUM_CLASS: 37

#  TXT_PATH: '/p300/dataset/COIN/splits/train_triplet.txt'
#  NUM_CLASS: 1396

#  TXT_PATH: '/p300/dataset/Diving48/splits/train_all1.txt'
#  NUM_CLASS: 20


  NUM_SAMPLE: 1600
  NUM_CLIP: 16
  LEN_CLIP: 1




