TRAIN:
  USE_CUDA: True
  MAX_EPOCH: 200
  DECAY_EPOCHS: 100
  DECAY_RATE: 0.1
  BATCH_SIZE: 8
  LR: 0.001
  DROPOUT: 0
#  GRAD_MAX_NORM: 10
#  USE_ADAMW: True
#  FIX_VIT_PROJECTION: True
#  SAVE_PATH: 'logs/test'
  SAVE_PATH: 'logs/resnet50_img-pre_lr0.001'

MODEL:
  BACKBONE: 'resnet50'
  BACKBONE_DIM: '2D'
  PRETRAIN: 'pretrained_models/resnet50-ImageNet.pth'
#  PRETRAIN_PATH: 'logs/resnet18_lr0.001_pretrain/save_models/30_checkpoint.tar'
  DIM_EMBEDDING: 128
#  TRANSFORMER: True
#  ALIGNMENT: True
#  COSFACE: True
  SAVE_EPOCHS: 1

DATASET:
  MODE: 'train'
  TXT_PATH: '/p300/dataset/ActionVerification/train_all.txt'
  NUM_CLASS: 45
  NUM_SAMPLE: 800
  NUM_CLIP: 16
  LEN_CLIP: 1




