TRAIN:
  USE_CUDA: True
  MAX_EPOCH: 200
  DECAY_EPOCHS: 100
  DECAY_RATE: 0.1
  BATCH_SIZE: 16
  LR: 0.0001
  DROPOUT: 0
#  GRAD_MAX_NORM: 1
#  USE_ADAMW: True
#  SAVE_PATH: 'logs/test'
  SAVE_PATH: 'logs/c3d_sports1m-pre_lr0.0001_new-sampler'

MODEL:
  BACKBONE: 'c3d'
  BACKBONE_DIM: '3D'
  PRETRAIN: 'pretrained_models/c3d_sports1m.pickle'
  DIM_EMBEDDING: 128
#  TRANSFORMER: True
#  ALIGNMENT: True
#  COSFACE: True
  SAVE_EPOCHS: 1

DATASET:
  MODE: 'train'
  TXT_PATH: '/p300/dataset/ActionVerification/train_all.txt'
  NUM_CLASS: 45
  NUM_SAMPLE: 800
  NUM_CLIP: 16
  LEN_CLIP: 1




