TRAIN:
  USE_CUDA: True
  MAX_EPOCH: 100
  DECAY_EPOCHS: 40
  DECAY_RATE: 0.1
  BATCH_SIZE: 16
  LR: 0.0001
  DROPOUT: 0
  PARTIAL_BN: False
  FREEZE_BACKBONE: False
  SEED: 1234
  SAVE_PATH: 'coin_logs/vit+vit+sa_lr0.0001'
#  SAVE_PATH: 'coin_logs/test'

MODEL:
  BACKBONE: 'cat'
  BACKBONE_DIM: '2D'
  BASE_MODEL: 'vit'
#  PRETRAIN: 'pretrained_models/resnet50-ImageNet.pth'
#  PRETRAIN: 'coin_logs/resnet50_img-pre_lr0.001/save_models/epoch_186.tar'
  DIM_EMBEDDING: 128
  TRANSFORMER: True
  ALIGNMENT: True
#  SEQ_LOSS_COEF: 0.1
#  COSFACE: True
  SAVE_EPOCHS: 1


DATASET:
  MODE: 'train'
#  TXT_PATH: '/p300/dataset/ActionVerification/train_all.txt'
#  NUM_CLASS: 45
#  NUM_SAMPLE: 800
  TXT_PATH: '/p300/dataset/COIN/train_all.txt'
  NUM_CLASS: 442
  NUM_SAMPLE: 1600
  NUM_CLIP: 16
  LEN_CLIP: 1
  SHUFFLE: True




