TRAIN:
  USE_CUDA: True
  MAX_EPOCH: 200
  DECAY_EPOCHS: 100
  DECAY_RATE: 0.1
  BATCH_SIZE: 8
  LR: 0.0001
  DROPOUT: 0
#  SAVE_PATH: 'logs/test'
  SAVE_PATH: 'logs/vgg+cos+vit+sa_img-pre_lr0.0001'

MODEL:
  BACKBONE: 'vgg'
  BACKBONE_DIM: '2D'
  PRETRAIN: 'pretrained_models/vgg16-ImageNet.pth'
  DIM_EMBEDDING: 128
  TRANSFORMER: True
  ALIGNMENT: True
  COSFACE: True
  SAVE_EPOCHS: 3

DATASET:
  MODE: 'train'
  TXT_PATH: '/p300/dataset/ActionVerification/train_all.txt'
  NUM_CLASS: 45
  NUM_SAMPLE: 800
  NUM_CLIP: 16
  LEN_CLIP: 1




